/*
 * File: app/store/StoreFinTree.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('School.store.StoreFinTree', {
    extend: 'Ext.data.TreeStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StoreFinTree',
            root: {
                expanded: true,
                children: [
                    {
                        text: 'الإدارة العامة',
                        expanded: true,
                        children: [
                            {
                                text: 'الدراسة العادية',
                                expanded: true,
                                children: [
                                    {
                                        name: 'fees',
                                        text: 'الرسوم',
                                        leaf: true
                                    }
                                ]
                            },
                            
                        ]
                    },
                    {
                        text: 'buy lottery tickets',
                        leaf: true
                    }
                ]
            },
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'text'
                }
            ]
        }, cfg)]);
    }
});