/*
 * File: app/store/StudentStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('School.store.UserStore', {
    extend: 'Ext.data.Store',

    requires: [
        'School.model.User'
    ],
    model: 'School.model.User',
    autoLoad: true,
    autoSync: true,
    storeId: 'MyJsonStore',
    proxy: {
        type: 'ajax',
        api: {
            //update: 'api/users/list'
            read: '/api/users/list', 
        },
        reader: {
            url: '/api/users/list', 
            type: 'json'
        },
        writer: {
            type: 'json'
        }
        
        }
    
});
