/*
 * File: app/view/MyPanel5.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('School.view.MyPanel5', {
    extend: 'Ext.panel.Panel',

    id: 'pnl_area_financial',
    itemId: 'pnl_area_financial',
    width: 754,
    layout: {
        align: 'middle',
        pack: 'center',
        type: 'hbox'
    },
    closable: true,
    title: 'المالية',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'treepanel',
                    flex: 1,
                    dock: 'left',
                    height: 425,
                    width: 332,
                    closable: true,
                    collapsed: false,
                    collapsible: true,
                    placeholderCollapseHideMode: 1,
                    title: 'الإدارة المالية',
                    store: 'StoreFinTree',
                    viewConfig: {

                    },
                    listeners: {
                        select: {
                            fn: me.onTreepanelSelect,
                            scope: me
                        }
                    }
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    height: 500,
                    itemId: 'finanGrid',
                    title: '',
                    store: 'StoreFinReport',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'amount',
                            text: 'Amount'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'text',
                            text: 'Text'
                        }
                    ],
                    listeners: {
                        select: {
                            fn: me.onGridpanelSelect1,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    id: 'formFee',
                    itemId: 'formFee',
                    tpl: [
                        '{name} <br/> {amount} <br/> {text}',
                        ''
                    ],
                    title: 'My Panel'
                }
            ]
        });

        me.callParent(arguments);
    },

    onTreepanelSelect: function(rowmodel, record, index, eOpts) {
        if(record.data.name=='fees') {

        }
    },

    onGridpanelSelect1: function(rowmodel, record, index, eOpts) {
        // this.down('#finanGrid').hide();
        // this.down('#formFee').show();

        var detailPanel = this.down('#formFee');
        // update the detailPanel with data
        // this will trigger the tpl to become updates
        detailPanel.update(record.data);


    }

});