/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('School.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    rtl: true,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    region: 'north',
                    border: false,
                    height: 40,
                    rtl: true,
                    layout: {
                        defaultMargins: {
                            top: 0,
                            right: 0,
                            bottom: 5,
                            left: 0
                        },
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'splitbutton',
                            rtl: false,
                            text: 'الطلاب',
                            menu: {
                                xtype: 'menu',
                                rtl: false,
                                headerPosition: 'bottom',
                                placeholderCollapseHideMode: 2,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        rtl: false,
                                        text: 'تسجيل طالب جديد',
                                        listeners: {
                                            click: {
                                                fn: me.onMenuitemClick,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'splitbutton',
                            icon: 'images/bricks.png',
                            iconCls: '',
                            text: 'العاملين',
                            listeners: {
                                click: {
                                    fn: me.onSplitbuttonClick2,
                                    scope: me
                                }
                            },
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'ادخال طالب جديد',
                                        listeners: {
                                            click: {
                                                fn: me.onMenuitemClick1,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'splitbutton',
                            icon: 'images/bricks.png',
                            iconCls: '',
                            text: 'الأكاديمية',
                            listeners: {
                                click: {
                                    fn: me.onSplitbuttonClick3,
                                    scope: me
                                }
                            },
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'ادخال طالب جديد',
                                        listeners: {
                                            click: {
                                                fn: me.onMenuitemClick2,
                                                scope: me
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'splitbutton',
                            icon: 'images/bricks.png',
                            text: 'اداريات',
                            listeners: {
                                click: {
                                    fn: me.onSplitbuttonClick1,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    collapseMode: 'header',
                    region: 'center',
                    id: 'pnl_tab_main',
                    itemId: 'pnl_tab_main',
                    animCollapse: false,
                    collapseFirst: false,
                    collapsible: false,
                    titleCollapse: false,
                    maxTabWidth: 100,
                    minTabWidth: 20,
                    items: [
                        {
                            xtype: 'panel',
                            id: 'pnl_area_student',
                            itemId: 'pnl_area_student',
                            rtl: true,
                            width: 754,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            tabConfig: {
                                xtype: 'tab',
                                flex: 1
                            },
                            dockedItems: [
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    margins: '10',
                                    dock: 'left',
                                    autoRender: true,
                                    width: 212,
                                    resizable: false,
                                    bodyBorder: true,
                                    animCollapse: true,
                                    collapseDirection: 'left',
                                    collapsed: false,
                                    collapsible: true,
                                    placeholderCollapseHideMode: 4,
                                    title: 'البحث عن طالب',
                                    titleAlign: 'right',
                                    titleCollapse: false,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            margin: '10 ',
                                            width: 200,
                                            fieldLabel: 'اسم الطلاب',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 200,
                                            fieldLabel: 'اسم العائلة',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'textfield',
                                            width: 200,
                                            fieldLabel: 'رقم الطالب',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'checkboxgroup',
                                            fieldLabel: 'الجنس',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'ذكر'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'انثى'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'الجنسية'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'الديانة'
                                        }
                                    ],
                                    listeners: {
                                        afterrender: {
                                            fn: me.onFormAfterRender,
                                            scope: me
                                        }
                                    }
                                }
                            ],
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    width: 271,
                                    layout: {
                                        align: 'stretch',
                                        padding: '',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            height: 181,
                                            width: 446,
                                            collapseDirection: 'left',
                                            collapsed: false,
                                            collapsible: true,
                                            title: 'كل الطلاب',
                                            titleCollapse: true,
                                            store: 'StudentStore',
                                            viewConfig: {
                                                padding: '0 0 0 5'
                                            },
                                            listeners: {
                                                select: {
                                                    fn: me.onGridpanelSelect,
                                                    single: false,
                                                    scope: me
                                                }
                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'id',
                                                    text: 'Student_id'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    editRenderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                                    },
                                                    dataIndex: 'firstname',
                                                    text: 'الأسم الأول',
                                                    editor: {
                                                        xtype: 'textfield',
                                                        name: 'Student[firstname]',
                                                        vtype: 'alpha'
                                                    }
                                                },
                                                {
                                                    xtype: 'actioncolumn',
                                                    items: [
                                                        {

                                                        }
                                                    ]
                                                }
                                            ],
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.CellEditing', {
                                                    listeners: {
                                                        edit: {
                                                            fn: me.onCellEditingEdit,
                                                            scope: me
                                                        }
                                                    }
                                                })
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            padding: '0 5 0 5',
                                            overflowX: 'scroll',
                                            overflowY: 'scroll',
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            manageHeight: false,
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    flex: 1,
                                                    overflowX: 'auto',
                                                    overflowY: 'auto',
                                                    layout: {
                                                        align: 'stretch',
                                                        type: 'vbox'
                                                    },
                                                    manageHeight: false,
                                                    items: [
                                                        {
                                                            xtype: 'form',
                                                            flex: 1,
                                                            margins: '10',
                                                            autoRender: true,
                                                            id: 'pnl_parent_info',
                                                            itemId: 'pnl_parent_info',
                                                            tpl: [
                                                                '<table>',
                                                                '    <tr>',
                                                                '        <td> الإسم </td>',
                                                                '        <td>',
                                                                '            {name} </td>',
                                                                '    </tr>',
                                                                '    ',
                                                                '    <tr>',
                                                                '        <td>رقم الهاتف</td>',
                                                                '        <td>',
                                                                '            {mobile} </td>',
                                                                '    </tr>',
                                                                '    ',
                                                                '    <tr>',
                                                                '        <td> البريد الإلكتروني </td>',
                                                                '        <td>',
                                                                '            {email} </td>',
                                                                '    </tr>',
                                                                '    ',
                                                                '</table>',
                                                                ''
                                                            ],
                                                            width: 212,
                                                            overflowX: 'auto',
                                                            overflowY: 'auto',
                                                            resizable: false,
                                                            bodyBorder: true,
                                                            animCollapse: true,
                                                            collapseDirection: 'top',
                                                            collapseFirst: false,
                                                            collapsed: false,
                                                            collapsible: true,
                                                            manageHeight: false,
                                                            placeholderCollapseHideMode: 2,
                                                            title: 'بيانات ولي الأمر',
                                                            titleCollapse: true
                                                        },
                                                        {
                                                            xtype: 'form',
                                                            flex: 1,
                                                            margins: '5 5 5 5',
                                                            height: 400,
                                                            id: 'pnl_student_info',
                                                            itemId: 'pnl_student_info',
                                                            margin: '5 5 5 5 ',
                                                            overflowX: 'auto',
                                                            overflowY: 'auto',
                                                            bodyPadding: 10,
                                                            collapseDirection: 'top',
                                                            collapsed: true,
                                                            collapsible: true,
                                                            title: 'بيانات شخصية',
                                                            titleCollapse: true,
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    anchor: '100%',
                                                                    fieldLabel: 'رقم الهاتف'
                                                                },
                                                                {
                                                                    xtype: 'textareafield',
                                                                    anchor: '100%',
                                                                    fieldLabel: 'العنوان كامل'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    anchor: '100%',
                                                                    fieldLabel: 'رقم هاتف ولي الأمر'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    anchor: '100%',
                                                                    fieldLabel: 'البريد الألكتروني لولي الأمر'
                                                                }
                                                            ],
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'button',
                                                                    dock: 'bottom',
                                                                    text: 'حفظ'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            flex: 1,
                                                            margins: '5 5 5 5 ',
                                                            margin: '5 5 5 5',
                                                            collapsed: true,
                                                            collapsible: true,
                                                            manageHeight: false,
                                                            title: 'My Panel',
                                                            titleCollapse: true,
                                                            items: [
                                                                {
                                                                    xtype: 'chart',
                                                                    itemId: 'scoreChart',
                                                                    width: 400,
                                                                    animate: true,
                                                                    insetPadding: 20,
                                                                    store: 'ScoreChart',
                                                                    axes: [
                                                                        {
                                                                            type: 'Category',
                                                                            fields: [
                                                                                'score'
                                                                            ],
                                                                            title: 'المواد',
                                                                            position: 'bottom'
                                                                        },
                                                                        {
                                                                            type: 'Numeric',
                                                                            fields: [
                                                                                'score'
                                                                            ],
                                                                            title: 'العلامات',
                                                                            maximum: 50,
                                                                            minimum: 0,
                                                                            position: 'left'
                                                                        }
                                                                    ],
                                                                    series: [
                                                                        {
                                                                            type: 'column',
                                                                            label: {
                                                                                display: 'insideEnd',
                                                                                field: 'y',
                                                                                color: '#333',
                                                                                'text-anchor': 'middle'
                                                                            },
                                                                            xField: 'name',
                                                                            yField: 'score'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            hidden: true,
                            id: 'pnl_student_reg',
                            itemId: 'pnl_student_reg',
                            bodyPadding: 10,
                            title: 'My Form',
                            jsonSubmit: true,
                            method: 'post',
                            standardSubmit: false,
                            url: 'http://localhost/test/index.php',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'الإسم الكامل'
                                },
                                {
                                    xtype: 'radiogroup',
                                    fieldLabel: 'الجنس',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'ذكر'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'انثى'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'تاريخ الميلاد'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'الجنسية'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'رقم الهاتف'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    fieldLabel: 'العنوان كامل',
                                    name: 'address'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'رقم هاتف ولي الأمر'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'البريد الإلكتروني'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'البريد الألكتروني لولي الأمر'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'button',
                                    dock: 'bottom',
                                    text: 'حفظ',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    width: 150,
                    animCollapse: true,
                    collapsed: true,
                    collapsible: true,
                    placeholderCollapseHideMode: 4,
                    title: 'الوصول السريع',
                    titleCollapse: false
                }
            ]
        });

        me.callParent(arguments);
    },

    onMenuitemClick: function(item, e, eOpts) {
        alert('a');
        this.down('#pnl_student_reg').show();
        alert('b');
        this.down('#pnl_student_reg').hidden = true;
        alert('d');
    },

    onSplitbuttonClick2: function(button, e, eOpts) {
        //this.down("*[id^=pnl_area_]").hide();
        //this.down("*[id^=pnl_area_financial]").hide();
        this.down('*[id^=pnl_area_student]').show();

    },

    onMenuitemClick1: function(item, e, eOpts) {
        alert('a');
        this.down('#pnl_student_reg').show();
        alert('b');
        this.down('#pnl_student_reg').hidden = true;
        alert('d');
    },

    onSplitbuttonClick3: function(button, e, eOpts) {
        //this.down("*[id^=pnl_area_]").hide();
        //this.down("*[id^=pnl_area_financial]").hide();
        this.down('*[id^=pnl_area_student]').show();

    },

    onMenuitemClick2: function(item, e, eOpts) {
        this.down('#pnl_student_reg').show();

    },

    onSplitbuttonClick1: function(button, e, eOpts) {
        //this.down('*[id^=pnl_area_]').hide();
        //this.down('*[id^=pnl_area_student]').hide();

        console.log(Ext.Ext.ComponentQuery.query('viewport') ) ;
        //Ext.select('School.view.MyPanel5'));

        //console.log(Ext.select('#pnl_tab_main')  );
        //Ext.select('#pnl_tab_main') .tabs.add( Ext.select('#pnl_area_financial'));
    },

    onFormAfterRender: function(component, eOpts) {

    },

    onGridpanelSelect: function(rowmodel, record, index, eOpts) {
        // grab a reference to the qualityChart, notice we use down here instead of child
        // because down will go down the container hierarchy at any depth and child
        // only retrieves direct children
        var chart = this.down('#scoreChart');
        // get the quality field out of this record
        var qualityData = record.get('score');
        console.log(record);	
        chart.store.loadData(qualityData);
        console.log( record.get('parent')  ) ;
        this.down('#pnl_parent_info').update(record.get('parent') );
        //this.down('#pnl_student_info').update (record.get('parent') );

    },

    onCellEditingEdit: function(editor, e, eOpts) {
        alert("you need to save");
        e.record.commit();
    },

    onButtonClick: function(button, e, eOpts) {

        var form = this.down('#pnl_student_reg');
        //var formData = form.getFieldValues();
        //Ext.Ajax.request({url: "http://localhost/test/index.php", method: "POST", data: formData});


        console.log(form);
        form.submit({
            success: function(response) {
                alert('Success');
            }, 
            failure: function(response) {
                alert('Failed');
            } } );



    }

});